### PR TITLE
Feature - bokeh server plotting

### PR DESCRIPTION
**Pull request by caryan**
Dramatically improves plotting performance but with some irritations:
1. have to ctrl-C or interrupt kernel
2. in-line notebook plotting not working - #61

### CODE REVIEW

**Comment by dieris** [comment]
Does the bokeh server need to be explicitly started? I'm getting `IOError: Cannot push session document because we failed to connect to the server (to start the server, try the 'bokeh serve' command)`

**Comment by caryan** [comment]
No, it should be spun off in a background thread [here](https://github.com/BBN-Q/QGL/blob/19d851bd57335d5f8c49d08ef3af8459ad8448fb/QGL/Plotting.py#L142).  It may be a Windows issue though.

**Comment by caryan** [comment]
It now runs in Windows but is dog slow.  Until I figure that out let's suspend this PR

**Comment by matthewware** [comment]
With the new plot server, this issue and branch is now obsolete

**Pull request closed without merging**
