### PR TITLE
Rescale gauss and drag shapes to max = amp

### PR DESCRIPTION
**Pull request by dieris**
For compatibility with QGL.jl. My tests are still not passing locally (even after updating the new sequences), but we need to fix this in one direction or the other.

### CODE REVIEW

**Comment by caryan** [comment]
OK, I'll fix this today

**Comment by dieris** [comment]
thanks

**Comment by blakejohnson** [comment]
We need to rebase this to pick up fixes for Bokeh from master.

**Comment by caryan** [comment]
Yep already rebased.

**Pull request merged**
