### PR TITLE
Support suppressing compilation for some Edges, Qubits

### PR DESCRIPTION
**Pull request by ahelsing**
Add arguments/logic to `compile_to_hardware` to allow specifying exactly which Edges and Qubit to compile pulses for; pulses on other Qubits and Edges (and their gates) will be suppressed.

Adds to `compile_to_hardware` the argument `edgesToCompile` which, if present, is a list of Edges to compile: pulses on any other edges will be skipped. Similarly, `qubitToCompile` if set will be the only Qubit whose pulses will be compiled; others will be skipped. And when skipping an Edge/Qubit, skip their gates as well.

This allows QGL2 to invoke `compile_to_hardware` once per AWG, and build up a set of HD5 files that do not overlap.

This is implemented by editing the list of channels used in `compile_sequence` with a new method `channelsToCompile`.

Also add a couple file extensions to `.gitignore`, clean up some logs, and add a couple comments.

### CODE REVIEW

**Comment by blakejohnson** [comment]
So, my comment about not dealing with "axis_descriptor" was not to remove it, but to simply let QGL1 do what it was already doing. You can just pass nothing from QGL2.

**Comment by ahelsing** [comment]
OK, I merged in the latest from QGL master, so this PR is now mergeable.

**Comment by blakejohnson** [comment]
Replaced by #79.

**Comment by blakejohnson** [comment]
Sorry, there were so many merge commits that I couldn't figure out what was going on here. So I started from a fresh master and cherry picked the relevant things. I'll merge the new PR once it passes CI.

**Pull request closed without merging**
