### PR TITLE
Allow ControlInstructions to take a channels argument

### PR DESCRIPTION
**Pull request by blakejohnson**
And use the passed `channels` to determine where it should broadcast. The specific use case I have in mind is `Wait(q1)`, `Wait(q2)`, etc.

Also introduces a `Store` instruction that I intend to be ignored from the compiler's perspective. But, it is nice for the human.

### CODE REVIEW

**Comment by blakejohnson** [comment]
Woah, coverage dropped dramatically. I must have really messed something up.

**Comment by blakejohnson** [comment]
In fact I had broken a bunch of things. Tests pass locally, let's try travis...

**Comment by blakejohnson** [comment]
Ping @caryan

**Comment by caryan** [comment]
Why did any of the unit test h5 files change?

**Comment by blakejohnson** [comment]
One note, this is technically a breaking change because `qwait('CMP')` now needs to be spelled `qwait(kind='CMP')`.

**Comment by caryan** [comment]
I'm having trouble actually using `qwait` on a channel.

```python
seqs = [[X90(q1), MEAS(q1), qwait(channel=q1), Id(q1, d), X90(q1)] for d in 10e-9*np.arange(1, 11)]
filenames = compile_to_hardware(seqs, "Test/Test")

/home/cryan/Programming/Repos/QGL/QGL/Compiler.py in compile_to_hardware(seqs, fileName, suffix, axis_descriptor, qgl2, addQGL2SlaveTrigger, edgesToCompile, qubitToCompile)
    356 
    357     # Compile all the pulses/pulseblocks to sequences of pulses and control flow
--> 358     wireSeqs = compile_sequences(seqs, channels, edgesToCompile=edgesToCompile, qubitToCompile=qubitToCompile)
    359 
    360     if not validate_linklist_channels(wireSeqs.keys()):

/home/cryan/Programming/Repos/QGL/QGL/Compiler.py in compile_sequences(seqs, channels, edgesToCompile, qubitToCompile)
    478 
    479     # use seqs[0] as prototype in case we were not given a set of channels
--> 480     wires = compile_sequence(seqs[0], channels, edgesToCompile, qubitToCompile)
    481     if not channels:
    482         channels = set(wires.keys())

/home/cryan/Programming/Repos/QGL/QGL/Compiler.py in compile_sequence(seq, channels, edgesToCompile, qubitToCompile)
    608         if isinstance(block, ControlFlow.ControlInstruction):
    609             block_channels = block.channel if block.channel else channels
--> 610             for chan in block_channels:
    611                 wires[chan] += [copy(block)]
    612             continue

TypeError: 'Qubit' object is not iterable
```

**Comment by blakejohnson** [comment]
Renamed `channel` to `channels` for `ControlInstructions`. So, expected usage is, e.g. `qwait(channels=(q1,))`.

**Comment by caryan** [comment]
I'm not sure why this is failing on Travis because it works locally. Trying again....

**Comment by caryan** [comment]
So on a rebuild Python 3 passes but Python 2 is still missing h5 files.  Must be a Travis issue.

**Pull request merged**
