### PR TITLE
Feature/aps2 firmware v4

### PR DESCRIPTION
**Pull request by caryan**

### CODE REVIEW

**Comment by caryan** [comment]
@dieris  I've merged master back to catch Blake's latest changes.

**Comment by blakejohnson** [comment]
@dieris this was not ready to merge.

**Comment by blakejohnson** [comment]
I'll try to figure out how to revert or fix it.

**Comment by blakejohnson** [comment]
@caryan assures me that he will fix the failing unit test.

**Comment by dieris** [comment]
oops, sorry about that!

**Pull request merged**
