### PR TITLE
Fix/bokeh column source

### PR DESCRIPTION
**Pull request by grahamrow**
Bokeh claims that ColumnDataSources cannot have columns with different lengths. Mysteriously, plotting of waveforms still worked for some people on some computers with some versions of bokeh. At any rate, we were using deprecated bokeh API commands, and needed a refresh anyways. Each sequence and channel get their own ColumnDataSource now.

@matthewware @dieris @gribeill could you try this out?

### CODE REVIEW

**Comment by dieris** [comment]
nicely working without column length warnings (you're right, I was ignoring them)! Except for single-segment though

**Comment by dieris** [comment]
Nevermind, working on lab PC, the issue is only on my laptop, looking into that...

**Comment by grahamrow** [comment]
I'll wait for a verdict on single sequences. Those shouldn't need the JS callback and therefor should be simpler! I'm on Bokeh 0.12.13 at this point FWIW.

**Comment by matthewware** [comment]
`output_file()` still works for me while `output_notebook()` does not.  I'm on your branch with bokeh 12.13.0.  Tried in Firefox and Chrome with no success.  I'll update when I know more.

**Comment by dieris** [comment]
@matthewware It works for me without calling `output_notebook`

**Comment by matthewware** [comment]
It works for me that way as well.  It just plots to a file and opens in a new browser tab which I'm totally fine with practically speaking.

**Pull request merged**
