### PR TITLE
Align trigger to left

### PR DESCRIPTION
**Pull request by dieris**
Fix alignment of digitizer trigger.
I understand this is not ideal, but I keep stumbling on this issue since https://github.com/BBN-Q/PyQLab/pull/88

### CODE REVIEW

**Comment by blakejohnson** [comment]
I think I'm ready to cave on this one, since it seems like a useful special case.

The only alternative that I see is adding `alignment` to the `Pulse`s rather than the `PulseBlock`s. That way, it would be legal to write:
```
align(MEAS(q1)*X(q2)) * TRIG(m-q1)
```

what do you think, @caryan?

**Comment by caryan** [comment]
I like @blakejohnson's suggestion.  As it is, `align` is kind of a useless function that just sets the `PulseBlock`'s alignment attribute.  If align took an alignment attribute and varags number of pulses and actually did the alignment with `Id`'s it might be more useful.

**Comment by dieris** [comment]
Replaced by https://github.com/BBN-Q/QGL/pull/157

**Comment by matthewware** [comment]
Deleting this branch given how stale it is and that it seems to have been merged in almost a year ago.

**Pull request closed without merging**
