### PR TITLE
CNOT implem. as edge property

### PR DESCRIPTION
**Pull request by dieris**
Replace https://github.com/BBN-Q/QGL/pull/137 
(Require https://github.com/BBN-Q/bbndb/tree/feature/CNOT-impl)

### CODE REVIEW

**Comment by dieris** [comment]
An alternative way to define `CNOT_implementation` per channel, instead of a global configuration. @ahelsing what do you think?

**Comment by ahelsing** [comment]
I see in #137 some comments about printing for the user what CNOT implementation is being used? Is that still relevant?

I guess I need you to help me understand what you're doing here.
- You changed the default CNOT from _simple to _CR? Why?
- Your new_edge function assumes there's a global "cnot_impl"? But where is that set? Or did you mean to include that as a keyword argument in the method signature?
- Is the idea that in the ChannelLibrary you would define on a per-edge basis what CNOT implementation to use?

Would anyone really use different implementations in a single experiment?
Why would the implementation be specific to the edge? Somehow tied to the hardware configuration?

**Comment by dieris** [comment]
We were discussing making the choice of CNOT a bit more flexible, and not being fixed for all the gates. We have never done that so far, but one could use different variations of CR (`echoCR` is just an example) or even entirely different gates depending on the circuit topology. 

* I changed the default implementation so that one doesn't have to define CNOT_CR for every single edge they create (although this could be a default value in `new_edge`, alternatively)
* I assumed we can still keep a global `cnot_impl` in QGL/config.py as a default
* Yes, optionally

**Comment by ahelsing** [comment]
In `config.py` the global seems to be `cnot_implementation`, not `cnot_impl`; I think that's why that test builds fail.

With the move to Auspex and with this change, I think there's a global default `CNOT`, but then you only get something else by setting the property on the edge, yes? Or can users still supply the `.json` config file and over-ride the default?

**Comment by dieris** [comment]
Yes, I think most of the time one doesn't need to change the global setting in `config.py`, but sometimes you may want to change the implementation for a particular gate (setting the edge property). There is no `.json` configuration left as far as I know

**Comment by ahelsing** [comment]
Perhaps add a comment in `config.py` that you can specify `channel.cnot_impl` to over-ride this global default on a per-Edge basis? Otherwise I worry this will get lost. 

On the corresponding change to `bbndb`: Is there a significant cost to adding the additional Column that will usually not be used? Perhaps also add a comment (in the `bbndb` change) that this should be a function name like `CNOT_CR`?

Have you tested with Edges that have the `cnot_impl` and those that do not?

**Pull request merged**
